In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import ModelCheckpoint
from sklearn import metrics
import os
%matplotlib inline
print(os.listdir("../dados/input"))

['BlackFriday.csv', 'BlackFriday.csv.zip', 'teste.csv', 'treino.csv']


In [5]:
original_data = pd.read_csv('../dados/input/BlackFriday.csv')


In [6]:
original_data.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [8]:
original_data['Product_Category_2'].fillna(0, inplace=True)
original_data['Product_Category_3'].fillna(0, inplace=True)

In [9]:
original_data['Product_Category_2'] = original_data['Product_Category_2'].astype(int)
original_data['Product_Category_3'] = original_data['Product_Category_3'].astype(int)

In [10]:
original_data.Stay_In_Current_City_Years = original_data.Stay_In_Current_City_Years.replace('4+',4)
original_data['Stay_In_Current_City_Years'] = original_data['Stay_In_Current_City_Years'].astype(int)

In [11]:
original_data.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

   Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                           2               0                   3   
1                           2               0                   1   
2                           2               0                  12   
3                           2               0                  12   
4                           4               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                   0                   0      8370  
1                   6                  14     15200  
2                   0                   0      1422  
3                  14                   0      1057  
4                   0                   0      7969

In [12]:
X = original_data.iloc[:,2:11].values
y = original_data.iloc[:,11].values

In [13]:
X

array([['F', '0-17', 10, ..., 3, 0, 0],
       ['F', '0-17', 10, ..., 1, 6, 14],
       ['F', '0-17', 10, ..., 12, 0, 0],
       ...,
       ['M', '36-45', 16, ..., 8, 15, 0],
       ['M', '36-45', 16, ..., 5, 0, 0],
       ['M', '36-45', 16, ..., 5, 8, 0]], dtype=object)

In [14]:
lb_x_1 = LabelEncoder()
X[:,0] = lb_x_1.fit_transform(X[:,0])
lb_x_2 = LabelEncoder()
X[:,1] = lb_x_2.fit_transform(X[:,1])
lb_x_4 = LabelEncoder()
X[:,3] = lb_x_2.fit_transform(X[:,3])
lb_x_3 = LabelEncoder()
X[:,2] = lb_x_3.fit_transform(X[:,2])

In [15]:
X

array([[0, 0, 10, ..., 3, 0, 0],
       [0, 0, 10, ..., 1, 6, 14],
       [0, 0, 10, ..., 12, 0, 0],
       ...,
       [1, 3, 16, ..., 8, 15, 0],
       [1, 3, 16, ..., 5, 0, 0],
       [1, 3, 16, ..., 5, 8, 0]], dtype=object)

In [16]:
onh = OneHotEncoder(categorical_features=[1,2,3])

In [17]:
X = onh.fit_transform(X).toarray()

In [21]:
print(X)

[[ 1.  0.  0. ...  3.  0.  0.]
 [ 1.  0.  0. ...  1.  6. 14.]
 [ 1.  0.  0. ... 12.  0.  0.]
 ...
 [ 0.  0.  0. ...  8. 15.  0.]
 [ 0.  0.  0. ...  5.  0.  0.]
 [ 0.  0.  0. ...  5.  8.  0.]]
